# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import imgpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('imgpost', '0002_remove_imgpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imgpost',
            name='imgurl',
            field=models.ImageField(height_field='height', upload_to=imgpost.models.user_directory_path, width_field='width'),
        ),
    ]
