# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgpost', '0003_auto_20170113_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpost',
            name='height',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='imgpost',
            name='width',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
