# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgpost', '0004_auto_20170113_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgPost',
        ),
        migrations.RemoveField(
            model_name='taggeditem',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
