# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-13 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imgpost.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('imgpost', '0005_auto_20170113_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('orientation', models.CharField(choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait'), ('Square', 'Square')], max_length=160)),
                ('description', models.TextField(null=True)),
                ('width', models.PositiveIntegerField(default=1, null=True)),
                ('height', models.PositiveIntegerField(default=1, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('imgurl', models.ImageField(height_field='height', upload_to=imgpost.models.user_directory_path, width_field='width')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tag', models.SlugField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
