# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='followers', to='accounts.UserProfile'),
        ),
    ]
