# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='head_shot',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocks',
            field=models.ManyToManyField(related_name='_userprofile_blocks_+', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='Description about me'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=320, null=True),
        ),
    ]
